CREATE TABLE username (
    ID_USER INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME_USER VARCHAR(50) NOT NULL UNIQUE,
    NAME_USER VARCHAR(100) NOT NULL,
    LASTNAME_USER VARCHAR(100) NOT NULL, 
    EMAIL_USER VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD_USER VARCHAR(255) NOT NULL,
    IMG_USER VARCHAR(255) NOT NULL
);

CREATE TABLE piece (
    ID_PIECE INT AUTO_INCREMENT PRIMARY KEY,
    NAME_PIECE VARCHAR(100) NOT NULL,
    TYPE_PIECE ENUM('top', 'bottom', 'dress', 'shoes', 'accessory') NOT NULL,
    COLOR_PIECE VARCHAR(50),
    IMG_PIECE VARCHAR(255) NOT NULL,
    ID_USER INT,
    FOREIGN KEY (ID_USER) REFERENCES username(ID_USER)
);

CREATE TABLE outfit (
    ID_OUTFIT INT AUTO_INCREMENT PRIMARY KEY,
    ID_PIECE1 INT,
    ID_PIECE2 INT,
    ID_USER INT,
    FOREIGN KEY (ID_PIECE1) REFERENCES piece(ID_PIECE), 
    FOREIGN KEY (ID_PIECE2) REFERENCES piece(ID_PIECE), 
    FOREIGN KEY (ID_USER) REFERENCES username(ID_USER)
);